sudo: false
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libboost-all-dev
    - os: osx
      osx_image: xcode9.2
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; export CXXFLAGS=-std=c++11; fi
before_script: 
  - mkdir build
script: cd build && cmake .. && make -j && make test
