language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      env: TOOL=clang-format
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-format-7
      compiler: clang
      branches:
        only:
          - dev
    - os: osx
      osx_image: xcode10
      env: TOOL=test
    - os: linux
      dist: xenial
      env: TOOL=test
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost-system1.58-dev
            - libboost-filesystem1.58-dev
            - libboost-test1.58-dev
            - libboost-program-options1.58-dev
    - os: linux
      dist: xenial
      env: TOOL=coverage
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
            - gcc-7
            - g++-7
            - cmake
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - libboost-system1.58-dev
            - libboost-filesystem1.58-dev
            - libboost-test1.58-dev
            - libboost-program-options1.58-dev
      branches:
        only:
          - dev
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_API_TOKEN
        local_dir: build/doc/html
        on:
          branch: dev
before_script: 
  - cd $TRAVIS_BUILD_DIR; mkdir build; cd build
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -DCMAKE_BUILD_TYPE=Debug;
    else
      if [[ $TOOL == "test" ]]; then cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8; fi;
      if [[ $TOOL == "coverage" ]]; then cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/gcc-7 -DCMAKE_CXX_COMPILER=/usr/bin/g++-7; fi
    fi
  - if [[ $TOOL == "test" ]] || [[ $TOOL == "coverage" ]]; then make -j; fi
  - if [[ $TOOL == "test" ]] || [[ $TOOL == "coverage" ]]; then make test; fi
  - if [[ $TOOL == "test" ]]; then make install; fi
  - if [[ $TOOL == "coverage" ]]; then make doc; fi
  - if [[ $TOOL == "clang-format" ]] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      cd $TRAVIS_BUILD_DIR;
      BASE_COMMIT=$(git rev-parse $TRAVIS_BRANCH);
      COMMIT_FILES=$(git diff --name-only $BASE_COMMIT | grep -i -v LinkDef);
      RESULT_OUTPUT="$(git-clang-format-7 --commit $BASE_COMMIT --diff --binary `which clang-format-7` $COMMIT_FILES)";
      if [ "$RESULT_OUTPUT" == "no modified files to format" ] || [ "$RESULT_OUTPUT" == "clang-format did not modify any files" ]; then
        echo "clang-format passed";
        exit 0;
      else
        echo "clang-format failed.";
        echo "$RESULT_OUTPUT";
        exit 1;
      fi
    fi
after_success:
  - if [[ $TOOL == "coverage" ]]; then cd ${TRAVIS_BUILD_DIR}/build; fi
  - if [[ $TOOL == "coverage" ]]; then lcov --directory . --capture --output-file coverage.info; fi
  - if [[ $TOOL == "coverage" ]]; then lcov --remove coverage.info '/opt/*' '/usr/*' --output-file coverage.info; fi
  - if [[ $TOOL == "coverage" ]]; then lcov --list coverage.info; fi
  - if [[ $TOOL == "coverage" ]]; then bash <(curl -s https://codecov.io/bash) || echo "No coverage reports"; fi
notifications:
  email: false
