sudo: required
language: cpp
dist: trusty
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
before_script: 
  - mkdir build
script: cd build && cmake .. && make -j && make test
