sudo: false
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libboost-dev
    - os: osx
      osx_image: xcode9.2
before_script: 
  - mkdir build
script: cd build && cmake .. && make -j && make test
