sudo: false
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libboost-all-dev
    - os: osx
      osx_image: xcode9.2
before_script: 
  - mkdir build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install -y cmake cmake-data g++ gcc make automake autoconf libtool libboost-all-dev; fi
script: cd build && cmake .. && make -j && make test
