sudo: required
language: cpp
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages: libboost-all-dev
    - os: osx
      osx_image: xcode9.2
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
before_script: 
  - mkdir build
script: cd build && cmake .. && make -j && make test
