sudo: false
language: cpp
matrix:
  include:
    - os: linux
     addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
before_install:
    - eval "${MATRIX_EVAL}"
before_script: 
  - mkdir build
  - export CXXFLAGS=-std=c++11; fi
script: cd build && cmake .. && make -j && make test
