Monitoring: AliceO2::Monitoring::Core::DataCollector Class Reference
AliceO2::Monitoring::Core::DataCollector Class Reference
Interface to Monitoring system.
#include <DataCollector.h>
Public Member Functions
DataCollector (std::string configurationFile)
Standard constructor.
virtual ~DataCollector ()
Destructor.
const std::string & getConfigurationFile () const
Get full path to configuration file.
void sendValue (std::string cluster, std::string node, std::string metric, int value)
Send integer value.
void sendValue (std::string cluster, std::string node, std::string metric, double value)
Send double value.
void sendValue (std::string cluster, std::string node, std::string metric, std::string value)
Send string value.
void sendTimedValue (std::string cluster, std::string node, std::string metric, int value, int timestamp)
Send timed integer value.
void sendTimedValue (std::string cluster, std::string node, std::string metric, double value, int timestamp)
Send timed double value.
void sendTimedValue (std::string cluster, std::string node, std::string metric, std::string value, int timestamp)
Send timed string value.
void log (int logLevel, std::string message)
Log message.
Private Member Functions
ApMon * getApMon () const
Get ApMon.
Private Attributes
const std::string mConfigurationFile
Path to configuration file.
std::string mCluster
Cluster name.
std::string mNode
Node name.
std::string mMetric
Metric name.
ApMon * mApMon
ApMon object.
Detailed Description
Interface to Monitoring system, allowing any process to send application-specific values
Constructor & Destructor Documentation
AliceO2::Monitoring::Core::DataCollector::DataCollector (std::string configurationFile)
Parameters:
configurationFile Path to configuration file
References mApMon.
AliceO2::Monitoring::Core::DataCollector::~DataCollector () [virtual]
References mApMon.
Member Function Documentation
ApMon * AliceO2::Monitoring::Core::DataCollector::getApMon () const [private]
Returns:
Return ApMon object
References mApMon.
Referenced by sendTimedValue(), and sendValue().
const std::string& AliceO2::Monitoring::Core::DataCollector::getConfigurationFile () const
Returns:
Return full path to configuration file
void AliceO2::Monitoring::Core::DataCollector::log (int logLevel, std::string message)
Parameters:
logLevel Log level
message Log message
void AliceO2::Monitoring::Core::DataCollector::sendTimedValue (std::string cluster, std::string node, std::string metric, std::string value, int timestamp)
This function can be used to send values measured in the past
Parameters:
cluster Cluster name
node Node name
metric Metric name
value Metric value
timestamp Timestamp of measurement in seconds
References getApMon().
void AliceO2::Monitoring::Core::DataCollector::sendTimedValue (std::string cluster, std::string node, std::string metric, double value, int timestamp)
This function can be used to send values measured in the past
Parameters:
cluster Cluster name
node Node name
metric Metric name
value Metric value
timestamp Timestamp of measurement in seconds
References getApMon().
void AliceO2::Monitoring::Core::DataCollector::sendTimedValue (std::string cluster, std::string node, std::string metric, int value, int timestamp)
This function can be used to send values measured in the past
Parameters:
cluster Cluster name
node Node name
metric Metric name
value Metric value
timestamp Timestamp of measurement in seconds
References getApMon().
void AliceO2::Monitoring::Core::DataCollector::sendValue (std::string cluster, std::string node, std::string metric, std::string value)
Parameters:
cluster Cluster name
node Node name
metric Metric name
value Metric value
References getApMon().
void AliceO2::Monitoring::Core::DataCollector::sendValue (std::string cluster, std::string node, std::string metric, double value)
Parameters:
cluster Cluster name
node Node name
metric Metric name
value Metric value
References getApMon().
void AliceO2::Monitoring::Core::DataCollector::sendValue (std::string cluster, std::string node, std::string metric, int value)
Parameters:
cluster Cluster name
node Node name
metric Metric name
value Metric value
References getApMon().
Member Data Documentation
ApMon* AliceO2::Monitoring::Core::DataCollector::mApMon [private]
Referenced by DataCollector(), getApMon(), and ~DataCollector().
std::string AliceO2::Monitoring::Core::DataCollector::mCluster [private]
const std::string AliceO2::Monitoring::Core::DataCollector::mConfigurationFile [private]
std::string AliceO2::Monitoring::Core::DataCollector::mMetric [private]
std::string AliceO2::Monitoring::Core::DataCollector::mNode [private]
The documentation for this class was generated from the following files:
/opt/devel/flp_prototype/hackathon/Monitoring/libs/Core/DataCollector.h
/opt/devel/flp_prototype/hackathon/Monitoring/libs/Core/DataCollector.cxx