name: Build and test

on: [pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install -yq libcurl-dev libboost-system1.65-dev libboost-filesystem1.65-dev libboost-test1.65-dev libboost-program-options1.65-dev
    - name: Run CMake
      run: mkdir build && cd build && cmake ..
    - name: Build project
      run: cd build && make -j
    - name: Test
      run: cd build && make test
