name: Compile on CC7

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: alisw/alibuild-action@master
        with:
          package: Monitoring
