name: Clang format

on: [pull_request]

jobs:
  clang-format-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -yq clang-format-8
    - name: Run clang-foramt on changed files
      run: |
        set -x
        echo ${{ github.base_ref }}
        BASE_COMMIT=$(git rev-parse ${{ github.base_ref }});
        COMMIT_FILES=$(git diff --name-only $BASE_COMMIT | grep -i -v LinkDef);
        RESULT_OUTPUT="$(git-clang-format-8 --commit $BASE_COMMIT --diff --binary `which clang-format-8` $COMMIT_FILES)";
        if [ "$RESULT_OUTPUT" == "no modified files to format" ] || [ "$RESULT_OUTPUT" == "clang-format did not modify any files" ] ; then
          exit 0;
        else
          echo -e "\tgit-clang-format-8 --commit $BASE_COMMIT --diff --binary $(which clang-format-8)"
          echo "$RESULT_OUTPUT";
          sleep 5;
          exit 1;
        fi  
